services:
  frontend:
    image: godoxy-frontend
    build: .
    container_name: godoxy-frontend-next
    restart: unless-stopped
    env_file: .env
    read_only: true
    tmpfs:
      - /app/.next/cache
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    labels:
      proxy.aliases: godoxy-next
      proxy.godoxy-next.rules: |
        - name: login page
          on: path /login
          do: pass
        - name: protected
          on: |
            !path regex("(_next/static|_next/image|favicon.ico).*")
            !path glob("/api/v1/auth/*")
            !path glob("/auth/*")
            !path regex("[A-Za-z0-9_-]+\.(svg|png|jpg|jpeg|gif|ico|webp|woff2?|eot|ttf|otf|txt)(\?.+)?")
            !path /api/v1/version
            !path /manifest.json
          do: require_auth
        - name: proxy to backend
          on: path glob("/api/v1/*")
          do: proxy http://$${API_ADDR}/
        - name: proxy to auth api
          on: path glob("/auth/*")
          do: |
            rewrite /auth /api/v1/auth
            proxy http://$${API_ADDR}/
