services:
  frontend:
    image: godoxy-webui
    build: .
    container_name: godoxy-frontend-next
    restart: unless-stopped
    network_mode: host # do not change this
    env_file: .env
    user: 1000:1000
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    environment:
      HOSTNAME: 127.0.0.1
      PORT: 3003
    labels:
      proxy.aliases: godoxy-next
      proxy.#1.port: 3003
