services:
  frontend:
    image: godoxy-frontend
    build: .
    container_name: godoxy-frontend-next
    restart: unless-stopped
    env_file: .env
    read_only: true
    tmpfs:
      - /tmp:rw
      - /app/node_modules/.cache:rw
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    labels:
      proxy.aliases: godoxy-next
