services:
  frontend:
    image: godoxy-webui
    build: .
    container_name: godoxy-frontend-next
    restart: unless-stopped
    env_file: .env
    read_only: true
    tmpfs:
      - /app/.next/cache
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    labels:
      proxy.aliases: godoxy-next
