// Generated by shadowtree gen-autocert-providers. Do not edit.
export type AutocertProvider =
  | 'acmedns'
  | 'azuredns'
  | 'clouddns'
  | 'cloudflare'
  | 'cloudns'
  | 'custom'
  | 'desec'
  | 'digitalocean'
  | 'dnsupdate'
  | 'duckdns'
  | 'edgedns'
  | 'gcloud'
  | 'godaddy'
  | 'hetzner'
  | 'hostinger'
  | 'httpreq'
  | 'infomaniak'
  | 'inwx'
  | 'ionos'
  | 'linode'
  | 'local'
  | 'namecheap'
  | 'netcup'
  | 'netlify'
  | 'oraclecloud'
  | 'ovh'
  | 'porkbun'
  | 'rfc2136'
  | 'scaleway'
  | 'spaceship'
  | 'timewebcloud'
  | 'vercel'
  | 'vultr'
import type { AutocertConfigBase, LocalOptions, CustomOptions } from './autocert'

// Go duration, for example 30s or 1m30s.
export type ProviderDuration = string

export interface AcmednsOptions extends AutocertConfigBase {
  provider: 'acmedns'
  options?: {
    api_base?: string
    allow_list?: Array<string>
    storage_path?: string
    storage_base_url?: string
  }
}

export interface AzurednsOptions extends AutocertConfigBase {
  provider: 'azuredns'
  options?: {
    zone_name?: string
    subscription_id?: string
    resource_group?: string
    private_zone?: boolean | 'true' | 'false'
    environment?: {
      active_directory_authority_host?: string
      services?: {
        [key: string]: {
          audience?: string
          endpoint?: string
        }
      }
    }
    client_id?: string
    client_secret?: string
    tenant_id?: string
    oidc_token?: string
    oidc_token_file_path?: string
    oidc_request_url?: string
    oidc_request_token?: string
    service_connection_id?: string
    system_access_token?: string
    auth_method?: string
    auth_msi_timeout?: ProviderDuration
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
    service_discovery_filter?: string
  }
}

export interface ClouddnsOptions extends AutocertConfigBase {
  provider: 'clouddns'
  options?: {
    client_id?: string
    email?: string
    password?: string
    ttl?: number | `${number}`
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
  }
}

export interface CloudflareOptions extends AutocertConfigBase {
  provider: 'cloudflare'
  options?: {
    auth_email?: string
    auth_key?: string
    auth_token?: string
    zone_token?: string
    base_url?: string
    ttl?: number | `${number}`
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
  }
}

export interface CloudnsOptions extends AutocertConfigBase {
  provider: 'cloudns'
  options?: {
    auth_id?: string
    sub_auth_id?: string
    auth_password?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface DesecOptions extends AutocertConfigBase {
  provider: 'desec'
  options?: {
    token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface DigitaloceanOptions extends AutocertConfigBase {
  provider: 'digitalocean'
  options?: {
    base_url?: string
    auth_token?: string
    ttl?: number | `${number}`
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
  }
}

export interface DnsupdateOptions extends AutocertConfigBase {
  provider: 'dnsupdate'
  options?: {
    nameserver?: string
    dns_timeout?: ProviderDuration
    zones?: Array<string>
    tsig_file?: string
    tsig_algorithm?: string
    tsig_key?: string
    tsig_secret?: string
    tsiggss_realm?: string
    tsiggss_username?: string
    tsiggss_password?: string
    tsiggss_keytab_file?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
    sequence_interval?: ProviderDuration
  }
}

export interface DuckdnsOptions extends AutocertConfigBase {
  provider: 'duckdns'
  options?: {
    token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    sequence_interval?: ProviderDuration
  }
}

export interface EdgednsOptions extends AutocertConfigBase {
  provider: 'edgedns'
  options?: {
    host?: string
    client_token?: string
    client_secret?: string
    access_token?: string
    account_key?: string
    header_to_sign?: Array<string>
    max_body?: number | `${number}`
    request_limit?: number | `${number}`
    debug?: boolean | 'true' | 'false'
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface GcloudOptions extends AutocertConfigBase {
  provider: 'gcloud'
  options?: {
    debug?: boolean | 'true' | 'false'
    project?: string
    zone_id?: string
    allow_private_zone?: boolean | 'true' | 'false'
    impersonate_service_account?: string
    access_token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface GodaddyOptions extends AutocertConfigBase {
  provider: 'godaddy'
  options?: {
    api_key?: string
    api_secret?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface HetznerOptions extends AutocertConfigBase {
  provider: 'hetzner'
  options?: {
    api_key?: string
    api_token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface HostingerOptions extends AutocertConfigBase {
  provider: 'hostinger'
  options?: {
    api_token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface HttpreqOptions extends AutocertConfigBase {
  provider: 'httpreq'
  options?: {
    endpoint?: {
      scheme?: string
      opaque?: string
      host?: string
      path?: string
      fragment?: string
      raw_query?: string
      raw_path?: string
      raw_fragment?: string
      force_query?: boolean | 'true' | 'false'
      omit_host?: boolean | 'true' | 'false'
    }
    mode?: string
    username?: string
    password?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
  }
}

export interface InfomaniakOptions extends AutocertConfigBase {
  provider: 'infomaniak'
  options?: {
    api_endpoint?: string
    access_token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface InwxOptions extends AutocertConfigBase {
  provider: 'inwx'
  options?: {
    username?: string
    password?: string
    shared_secret?: string
    sandbox?: boolean | 'true' | 'false'
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface IonosOptions extends AutocertConfigBase {
  provider: 'ionos'
  options?: {
    api_key?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface LinodeOptions extends AutocertConfigBase {
  provider: 'linode'
  options?: {
    token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
    http_timeout?: ProviderDuration
  }
}

export interface NamecheapOptions extends AutocertConfigBase {
  provider: 'namecheap'
  options?: {
    base_url?: string
    api_user?: string
    api_key?: string
    client_ip?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface NetcupOptions extends AutocertConfigBase {
  provider: 'netcup'
  options?: {
    key?: string
    password?: string
    customer?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
  }
}

export interface NetlifyOptions extends AutocertConfigBase {
  provider: 'netlify'
  options?: {
    token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface OraclecloudOptions extends AutocertConfigBase {
  provider: 'oraclecloud'
  options?: {
    compartment_id?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface OvhOptions extends AutocertConfigBase {
  provider: 'ovh'
  options?: {
    api_endpoint?: string
    application_key?: string
    application_secret?: string
    consumer_key?: string
    oauth2_config?: {
      client_id?: string
      client_secret?: string
    }
    access_token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface PorkbunOptions extends AutocertConfigBase {
  provider: 'porkbun'
  options?: {
    api_key?: string
    secret_api_key?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface Rfc2136Options extends AutocertConfigBase {
  provider: 'rfc2136'
  options?: {
    nameserver?: string
    dns_timeout?: ProviderDuration
    zones?: Array<string>
    tsig_file?: string
    tsig_algorithm?: string
    tsig_key?: string
    tsig_secret?: string
    tsiggss_realm?: string
    tsiggss_username?: string
    tsiggss_password?: string
    tsiggss_keytab_file?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
    sequence_interval?: ProviderDuration
  }
}

export interface ScalewayOptions extends AutocertConfigBase {
  provider: 'scaleway'
  options?: {
    project_id?: string
    secret_key?: string
    access_key?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface SpaceshipOptions extends AutocertConfigBase {
  provider: 'spaceship'
  options?: {
    api_key?: string
    api_secret?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export interface TimewebcloudOptions extends AutocertConfigBase {
  provider: 'timewebcloud'
  options?: {
    auth_token?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
  }
}

export interface VercelOptions extends AutocertConfigBase {
  provider: 'vercel'
  options?: {
    auth_token?: string
    team_id?: string
    ttl?: number | `${number}`
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
  }
}

export interface VultrOptions extends AutocertConfigBase {
  provider: 'vultr'
  options?: {
    api_key?: string
    propagation_timeout?: ProviderDuration
    polling_interval?: ProviderDuration
    ttl?: number | `${number}`
  }
}

export type AutocertConfigWithoutExtra =
  | LocalOptions
  | CustomOptions
  | AcmednsOptions
  | AzurednsOptions
  | ClouddnsOptions
  | CloudflareOptions
  | CloudnsOptions
  | DesecOptions
  | DigitaloceanOptions
  | DnsupdateOptions
  | DuckdnsOptions
  | EdgednsOptions
  | GcloudOptions
  | GodaddyOptions
  | HetznerOptions
  | HostingerOptions
  | HttpreqOptions
  | InfomaniakOptions
  | InwxOptions
  | IonosOptions
  | LinodeOptions
  | NamecheapOptions
  | NetcupOptions
  | NetlifyOptions
  | OraclecloudOptions
  | OvhOptions
  | PorkbunOptions
  | Rfc2136Options
  | ScalewayOptions
  | SpaceshipOptions
  | TimewebcloudOptions
  | VercelOptions
  | VultrOptions

export type AutocertExtra =
  | Partial<LocalOptions>
  | Partial<CustomOptions>
  | Partial<AcmednsOptions>
  | Partial<AzurednsOptions>
  | Partial<ClouddnsOptions>
  | Partial<CloudflareOptions>
  | Partial<CloudnsOptions>
  | Partial<DesecOptions>
  | Partial<DigitaloceanOptions>
  | Partial<DnsupdateOptions>
  | Partial<DuckdnsOptions>
  | Partial<EdgednsOptions>
  | Partial<GcloudOptions>
  | Partial<GodaddyOptions>
  | Partial<HetznerOptions>
  | Partial<HostingerOptions>
  | Partial<HttpreqOptions>
  | Partial<InfomaniakOptions>
  | Partial<InwxOptions>
  | Partial<IonosOptions>
  | Partial<LinodeOptions>
  | Partial<NamecheapOptions>
  | Partial<NetcupOptions>
  | Partial<NetlifyOptions>
  | Partial<OraclecloudOptions>
  | Partial<OvhOptions>
  | Partial<PorkbunOptions>
  | Partial<Rfc2136Options>
  | Partial<ScalewayOptions>
  | Partial<SpaceshipOptions>
  | Partial<TimewebcloudOptions>
  | Partial<VercelOptions>
  | Partial<VultrOptions>
